# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e120d1c8a9e15ce400dcfafa0cf6b38d322c449914953b2eb4ba3e18a548794a0947cece95e8c41e446566194e530d3b05892885c2ec2d8ea066cfae2df83ed

test:
  secret_key_base: f5b5fdd24a9650788ffa17277b1b221a17391a1fef56989c800ed9e5bcc8ef407c32767043505eb0908890881b1a4386527231d3c1f614b7e622085b0dd58a18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
